server:
  port: 4000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: hongkyu
    password: P!ssw0rd

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

secret-key: S3cr3tK3y

oauth2:
  google:
    client-id: 클라이언트 ID
    client-secret: 클라이언트 SECRET
    redirect-uri: http://localhost:4000/login/oauth2/code/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
  kakao:
    client-id: 클라이언트 ID
    admin-key: 어드민 KEY
    redirect-uri: http://localhost:4000/login/oauth2/code/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    resource-uri: https://kapi.kakao.com/v2/user/me
  naver:
    client-id: 클라이언트 ID
    client-secret: 클라이언트 SECRET
    redirect-uri: http://localhost:4000/login/oauth2/code/naver
    token-uri: https://nid.naver.com/oauth2.0/token
    resource-uri: https://openapi.naver.com/v1/nid/me
